spring:
  profiles:
    active: DEV
  application:
    name: TKM Spring Cloud Sample Service
  data:
    mongodb:
      uri: mongodb+srv://devuser:AadRZuPod0McUtP1@cluster0-qlt1t.mongodb.net/sample_spring_cloud?retryWrites=true&w=majority